version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - user
      - order
    networks:
      - api_net
    restart: unless-stopped

  auth:
    build: .
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSLMODE=disable
    command: uvicorn auth_service.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api_net
    restart: on-failure

  user:
    build: .
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSLMODE=disable
    command: uvicorn user_service.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api_net
    restart: on-failure

  order:
    build: .
    expose:
      - "8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - USER_SERVICE_URL=http://user:8000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSLMODE=disable
    command: uvicorn order_service.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
      user:
        condition: service_started
    networks:
      - api_net
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - api_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # потом удалить !!!!!!!!!!!!!!!
  # ports:
  #   - "5432:5432"

volumes:
  postgres_data:

networks:
  api_net:
    driver: bridge