version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: secure_db 
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1231}
      - POSTGRES_DB=${POSTGRES_DB:-api_secure_db}
    volumes:
      - pgdata:/var/lib/postgresql/data  # ← ИСПРАВЛЕНО: имя_тома:путь
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-api_secure_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth:
    build: . 
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-danil_kolbasenko}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-1231}@db:5432/${POSTGRES_DB:-api_secure_db}
    command: uvicorn auth_service.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

  user:
    build: .
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-danil_kolbasenko}
      - USER_SERVICE_URL=http://user:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-1231}@db:5432/${POSTGRES_DB:-api_secure_db}
    command: uvicorn user_service.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

  order:
    build: .
    ports:
      - "8002:8000"
    environment:
      - USER_SERVICE_URL=http://user:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-1231}@db:5432/${POSTGRES_DB:-api_secure_db}
    command: uvicorn order_service.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  pgdata:  # ← Объявляем именованный том здесь